In [1]:
import pandas as pd

df = pd.read_csv("../data/cleaned/pokemon_cleaned.csv")

In [2]:
df['Is_Special'] = df[['Legendary', 'Mythical', 'Pseudo_Legendary']].any(axis=1)

df['Total_Power'] = df[['HP','Attack','Defense','Special_Attack','Special_Defense','Speed']].sum(axis=1)

In [3]:
y = df['Is_Special']

In [4]:
X = df.drop(columns=[
    'Is_Special',
    'Legendary',
    'Mythical',
    'Pseudo_Legendary',
    'Name',
    'Abilities',
    'ID'
], errors='ignore')

In [5]:
X = pd.get_dummies(X, columns=['Type_1', 'Type_2'], drop_first=True)

In [6]:
X = X.select_dtypes(include=['number'])

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [8]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [9]:
y_pred = model.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9777777777777777
              precision    recall  f1-score   support

       False       0.99      0.99      0.99       164
        True       0.88      0.88      0.88        16

    accuracy                           0.98       180
   macro avg       0.93      0.93      0.93       180
weighted avg       0.98      0.98      0.98       180

## Model Evaluation: Logistic Regression

The Logistic Regression model achieved an overall accuracy of approximately 97.7%.

However, due to class imbalance (fewer special Pokémon), accuracy alone is not a sufficient metric.

Key observations:
- The model performs very well on non-special Pokémon (majority class)
- For special Pokémon:
  - Precision: 0.88
  - Recall: 0.88

This indicates that the model is able to correctly identify most special Pokémon, although some are still misclassified.

Overall, the model demonstrates strong performance, but there is room for improvement, particularly in identifying all special Pokémon.

In [11]:
import pandas as pd

feature_importance = pd.Series(model.coef_[0], index=X.columns)
feature_importance.sort_values(ascending=False).head(10)

Total_Power        0.044266
Speed              0.020767
Special_Defense    0.011283
Defense            0.010806
HP                 0.005506
Attack            -0.001230
Special_Attack    -0.002866
dtype: float64

## Insight: Feature Importance (Logistic Regression)

The model coefficients suggest that Total Power has the strongest positive influence on predicting whether a Pokémon is special.

Individual stats such as Attack, Special Attack, and Defense show smaller and sometimes negative coefficients. This is likely due to multicollinearity, as Total Power is derived from these stats and captures their combined effect.

Additionally, the presence of features like ID (which have no real predictive meaning) indicates the importance of careful feature selection.

Overall, the model relies more on combined strength rather than any single stat to make predictions.

In [12]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [13]:
y_pred_rf = rf_model.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

Accuracy: 0.9777777777777777
              precision    recall  f1-score   support

       False       0.99      0.99      0.99       164
        True       0.88      0.88      0.88        16

    accuracy                           0.98       180
   macro avg       0.93      0.93      0.93       180
weighted avg       0.98      0.98      0.98       180

In [15]:
import pandas as pd

feature_importance_rf = pd.Series(rf_model.feature_importances_, index=X.columns)
feature_importance_rf.sort_values(ascending=False).head(10)

Total_Power        0.559167
Speed              0.092112
Special_Attack     0.084831
Special_Defense    0.077479
HP                 0.075605
Attack             0.058440
Defense            0.052365
dtype: float64

## Model Comparison: Logistic Regression vs Random Forest

Both Logistic Regression and Random Forest models achieved similar performance:

- Accuracy: ~97.7%
- Precision (Special): 0.88
- Recall (Special): 0.88

This suggests that the underlying patterns in the data are strong but limited, and more complex models do not significantly improve performance.

### Feature Importance (Random Forest)

The most important features identified by the Random Forest model are:

- Total Power (dominant feature)
- Speed
- Special Attack
- Special Defense
- HP

This indicates that overall strength (Total Power) plays the most significant role in determining whether a Pokémon is classified as special.

Secondary attributes such as speed and special stats also contribute, suggesting that special Pokémon tend to be both powerful and well-rounded.

Overall, the model confirms that classification is driven by a combination of features rather than any single stat alone.

In [16]:
rf_model = RandomForestClassifier(
    random_state=42,
    class_weight='balanced'
)

In [17]:
y_pred = model.predict(X_test)

In [18]:
y_prob = model.predict_proba(X_test)[:, 1]

In [19]:
y_pred_adjusted = (y_prob > 0.3).astype(int)

## Improving Recall for Special Pokémon

The initial models achieved strong overall accuracy but missed some special Pokémon (recall = 0.88).

To improve recall, two approaches can be applied:

1. **Class Weight Adjustment**  
   By assigning higher importance to the minority class (special Pokémon), the model becomes more sensitive to detecting them.

2. **Threshold Adjustment**  
   Lowering the decision threshold increases the likelihood of classifying a Pokémon as special, improving recall at the cost of precision.

These techniques highlight the trade-off between precision and recall, where improving one may reduce the other.

In [20]:
rf_model = RandomForestClassifier(
    random_state=42,
    class_weight='balanced'
)

In [21]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_adjusted))

              precision    recall  f1-score   support

       False       0.99      0.99      0.99       164
        True       0.88      0.88      0.88        16

    accuracy                           0.98       180
   macro avg       0.93      0.93      0.93       180
weighted avg       0.98      0.98      0.98       180

In [22]:
y_prob[:20]

array([3.08963852e-03, 7.01875638e-01, 2.50877842e-05, 1.99590688e-02,
       5.51073951e-04, 2.63253447e-07, 7.77437206e-01, 3.58241285e-03,
       6.99405088e-07, 9.84406046e-05, 1.42773644e-05, 1.09403210e-01,
       5.55820254e-04, 4.14269463e-06, 2.66613052e-01, 3.94610199e-02,
       5.49930392e-03, 3.13620724e-04, 8.55456194e-01, 7.66486601e-06])

In [23]:
import numpy as np

np.min(y_prob), np.max(y_prob)

(np.float64(7.110312079355901e-09), np.float64(0.9944205515684499))

In [24]:
y_pred_adjusted = (y_prob > 0.1).astype(int)

In [25]:
print(classification_report(y_test, y_pred_adjusted))

              precision    recall  f1-score   support

       False       0.99      0.91      0.95       164
        True       0.48      0.88      0.62        16

    accuracy                           0.91       180
   macro avg       0.73      0.89      0.78       180
weighted avg       0.94      0.91      0.92       180

## Threshold Adjustment Analysis

Lowering the decision threshold from 0.5 to 0.1 did not improve recall for special Pokémon, which remained at 0.88.

However, precision dropped significantly from 0.88 to 0.48, and overall accuracy decreased.

This indicates that the model is already making confident predictions, and the remaining misclassified cases are not borderline instances that can be recovered by adjusting the threshold.

Instead, these errors likely arise from inherent overlap in the feature space, where some non-special Pokémon resemble special ones and vice versa.

This highlights a key limitation of the dataset and feature set.

In [26]:
results = X_test.copy()

results['Actual'] = y_test.values
results['Predicted'] = y_pred_rf   

misclassified = results[results['Actual'] != results['Predicted']]

misclassified.head()

,HP,Attack,Defense,Special_Attack,Special_Defense,Speed,Total_Power,Actual,Predicted
361,80,80,80,80,80,80,480,False,True
807,46,65,65,55,35,34,300,True,False
772,95,95,95,95,95,95,570,False,True
789,43,29,131,29,131,37,400,True,False

In [27]:
original = df.loc[misclassified.index]

original[['Name', 'Type_1', 'Total_Power', 'Is_Special']]

         Name   Type_1  Total_Power  Is_Special
361    glalie      ice          480       False
807    meltan    steel          300        True
772  silvally   normal          570       False
789   cosmoem  psychic          400        True

In [28]:
false_negatives = original[
    (results['Actual'] == True) & (results['Predicted'] == False)
]

false_positives = original[
    (results['Actual'] == False) & (results['Predicted'] == True)
]

C:\Users\Mayank\AppData\Local\Temp\ipykernel_6824\1694072504.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  false_negatives = original[
C:\Users\Mayank\AppData\Local\Temp\ipykernel_6824\1694072504.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  false_positives = original[

In [29]:
misclassified = X_test.copy()

misclassified['Actual'] = y_test.values
misclassified['Predicted'] = y_pred_rf

misclassified_original = df.loc[misclassified.index]

misclassified_original['Actual'] = misclassified['Actual']
misclassified_original['Predicted'] = misclassified['Predicted']

false_negatives = misclassified_original[
    (misclassified_original['Actual'] == True) &
    (misclassified_original['Predicted'] == False)
]

false_positives = misclassified_original[
    (misclassified_original['Actual'] == False) &
    (misclassified_original['Predicted'] == True)
]

In [30]:
false_negatives[['Name', 'Type_1', 'Total_Power']]

        Name   Type_1  Total_Power
807   meltan    steel          300
789  cosmoem  psychic          400

In [31]:
false_positives[['Name', 'Type_1', 'Total_Power']]

         Name  Type_1  Total_Power
361    glalie     ice          480
772  silvally  normal          570

## Insight: Misclassification Analysis

The analysis of misclassified Pokémon reveals two key patterns:

### False Negatives (Missed Special Pokémon)
Some special Pokémon, such as Meltan and Cosmoem, have relatively low total power. As a result, the model fails to identify them as special because they do not follow the general pattern of high strength.

### False Positives (Incorrectly Classified as Special)
Some non-special Pokémon, such as Glalie and Silvally, have high total power. These Pokémon resemble special Pokémon in terms of strength, leading the model to incorrectly classify them.

### Overall Observation
The model relies heavily on strength-related features (Total Power and stats). However, not all special Pokémon are strong, and not all strong Pokémon are special.

This overlap in feature space creates inherent limitations in classification performance, which cannot be fully resolved using the current features.